### ISSUE TITLE
Make showing progress a threshold

### ISSUE THREAD

**Issue by aschmois** [tfausak/purple-yolk#22]
The new progress is fantastic to figure out if PY is "working" but it can get a little overwhelming (especially sometimes hiding console output) on every save. I was thinking making a threshold config that after x amount of seconds spent reloading the progress pops up. This allows devs to fine tune their preference for instant feedback or only lagging feedback.

**Comment by tfausak** [comment]
I would like to implement this. I think there is a workaround though: When the progress is showing, you can hide it by pressing escape. That changes it from a `Notification` progress type to a `Window` progress type, which shows in the status bar. 

In terms of configurability, I will probably start with a hard coded threshold like one second. That way feedback is quick but not instant. Short-running commands won't show notifications at all, but long-running commands will.
