### ISSUE TITLE
Allow interacting with GHCi directly

### ISSUE THREAD

**Issue by tfausak** [tfausak/purple-yolk#6]
Since Purple Yolk keeps a GHCi session active, it would be nice to allow the user to use it too. This could be a regular looking terminal based REPL session, or maybe you could highlight text and send it to GHCi for evaluation. 

This is potentially tricky because it's possible to get GHCi in a bad state by sending it arbitrary commands. Having an escape hatch (#2) would make the more palatable.

**Comment by tfausak** [comment]
I think @codygman might like this. (Except that he uses Emacs, so Purple Yolk might not be too useful to him :stuck_out_tongue_closed_eyes:)

Another complicating factor is that you may want to be dropped into a GHCi session for an open file rather than the whole project. Maybe I could start with a project REPL and then add a file REPL later if that's wanted.

**Comment by codygman** [comment]
@tfausak You are right, I do like this idea a lot.

I've been meaning to get to trying purple yolk out in vscode soon™. 

That'll let me know if I can justify exploring what an emacs binding would look like.

**Comment by tfausak** [comment]
Even though Purple Yolk is a language server, I'm not making any promises about it being useful for programs other than VSCode.

**Comment by tfausak** [comment]
Realistically I don't think I'm going to implement this.
