### ISSUE TITLE
Report problems to the Problems tab in VSCode

### ISSUE THREAD

**Issue by gera-cameron** [tfausak/purple-yolk#7]
![image](https://user-images.githubusercontent.com/12397038/75262073-fb020000-57b9-11ea-8abf-ccf2a5d6afc0.png)

**Comment by tfausak** [comment]
Works on my machine :stuck_out_tongue_closed_eyes: 

![image](https://user-images.githubusercontent.com/408753/75267537-5f29c180-57c4-11ea-89c8-54bc37ba3402.png)

**Comment by tfausak** [comment]
I think the root cause is the same as #2. If the package changes in some fundamental way, Purple Yolk stops reporting anything. This situation can easily happen when switching Git branches or adding/removing modules.

**Comment by gera-cameron** [comment]
Nvm had a stale state.

**Comment by tfausak** [comment]
No problem! I think this is a good example of how #2 can manifest itself in different ways. Also this is a situation that could be helped by better reporting (#3).
