### ISSUE TITLE
Errors are not removed from PROBLEMS tab after they is fixed (Stack project)

### ISSUE THREAD

**Issue by EduardSergeev** [tfausak/purple-yolk#76]
When Stack project is loaded using this extension any GHC error seems to get stuck in `PROBLEMS` tab even after it is fixed and the affected file is saved.
What is more if you again introduce the same error and fix it (repeatedly) the same error message in `PROBLEMS` appears multiple times, e.g.:

![image](https://github.com/tfausak/purple-yolk/assets/722409/15ee7d7f-b1f4-4228-9474-a24bc070681e)

Reloading the project (via VSCode restart or via "Purple Yolk: Start Interpreter" command) does remove all "stale" error messages but the errors should be removed from `PROBLEMS` tab as soon as they are fixed and the file is saved.

**Comment by tfausak** [comment]
Weird. This works as expected for Cabal projects. I wonder if this is related to #43.

**Comment by tfausak** [comment]
Thanks for reporting! Should be fixed in [version 1.0.5](https://github.com/tfausak/purple-yolk/releases/tag/1.0.5).
